In [7]:
# AI Forensics — Dataset Audit

# Data manipulation
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# File and path handling
from pathlib import Path

# Image handling
from PIL import Image

# Progress bars
from tqdm.auto import tqdm

# System / reproducibility
import os
import sys
import random

# Display
from IPython.display import display

In [8]:
df = pd.read_csv(TRAIN_PATH)

print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

Shape: (1317236, 7)

Columns:
['Image Path', 'Predicted Gender', 'Predicted Age', 'Skin Tone', 'Target', 'Skin Tone Group', 'Intersection']

In [9]:
df.head()

,Image Path,Predicted Gender,Predicted Age,Skin Tone,Target,Skin Tone Group,Intersection
0,/AI_Face_imagesV2/DMs/DCFACe/7856/6.jpg,1,3,6,1,1,4
1,/AI_Face_imagesV2/deepfakes/celebdf/crop_img/0...,0,3,5,1,1,1
2,/AI_Face_imagesV2/GANs/ProGAN images/zip099000...,0,2,5,1,1,1
3,/AI_Face_imagesV2/DMs/DCFACe/4103/44.jpg,1,1,6,1,1,4
4,/AI_Face_imagesV2/DMs/DCFACe/9857/16.jpg,1,2,6,1,1,4

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1317236 entries, 0 to 1317235
Data columns (total 7 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   Image Path        1317236 non-null  object
 1   Predicted Gender  1317236 non-null  int64
 2   Predicted Age     1317236 non-null  int64
 3   Skin Tone         1317236 non-null  int64
 4   Target            1317236 non-null  int64
 5   Skin Tone Group   1317236 non-null  int64
 6   Intersection      1317236 non-null  int64
dtypes: int64(6), object(1)
memory usage: 70.3+ MB

In [12]:
df["Source"] = df["Image Path"].str.split("/").str[3]

df["Source"].value_counts()

Source
DCFACe                        424452
imdb_wiki                     191096
celebdf                       143530
ff++                          101564
StyleGAN2                      94660
ProGAN images                  79969
dfdc                           60174
FFHQ                           56047
taming_transformer_VQGAN       39943
dfd                            32156
stylegan3                      21416
StableDiffusion_Inpainting     16749
latent_diffusion               15917
StableDiffusion1.5             14428
STYLEGAN                        7978
AttGAN                          4823
Palette                         4804
STARGAN                         4482
STGAN                            810
MSG_STYLE_GAN                    803
MMD_GAN                          795
CommercialTools                  640
Name: count, dtype: int64

In [14]:
source_target.rename(
    columns={0: "Real", 1: "Fake"}
)

Target                        Real    Fake
Source
AttGAN                           0    4823
CommercialTools                  0     640
DCFACe                           0  424452
FFHQ                         56047       0
MMD_GAN                          0     795
MSG_STYLE_GAN                    0     803
Palette                          0    4804
ProGAN images                    0   79969
STARGAN                          0    4482
STGAN                            0     810
STYLEGAN                         0    7978
StableDiffusion1.5               0   14428
StableDiffusion_Inpainting       0   16749
StyleGAN2                        0   94660
celebdf                      18883  124647
dfd                           7095   25061
dfdc                         30136   30038
ff++                         17218   84346
imdb_wiki                   191096       0
latent_diffusion                 0   15917
stylegan3                        0   21416
taming_transformer_VQGAN         0   39943

In [16]:
df["Target"].value_counts(normalize=True) * 100

Target
1    75.670647
0    24.329353
Name: proportion, dtype: float64